# Modeling

In [1]:
%load_ext autoreload
%autoreload 2

import matplotlib.pyplot as plt
import seaborn as sns
import sqlite3 as sql
from ydata_profiling import ProfileReport
import modin.pandas as pd
import modin.config as modin_config

from utils import load_pickle_file, save_pickle_file
from tqdm.notebook import tqdm
modin_config.Engine.put("dask")

/home/programming/miniconda3/envs/grainger/lib/python3.10/site-packages/numba/core/decorators.py:262: NumbaDeprecationWarning: numba.generated_jit is deprecated. Please see the documentation at: https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-generated-jit for more information and advice on a suitable replacement.
  warnings.warn(msg, NumbaDeprecationWarning)
/home/programming/miniconda3/envs/grainger/lib/python3.10/site-packages/visions/backends/shared/nan_handling.py:51: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def hasna(x: np.ndarray) -> bool:


In [2]:
# conn = sql.connect('../data/grainger.db')
# searches_class = pd.read_sql_query("""SELECT * FROM search_terms""", con=conn, dtype=object)

In [3]:
# read in the training and testing data
x_train = load_pickle_file('../data/x_train_vectorized.pkl')
x_test = load_pickle_file('../data/x_test_vectorized.pkl')

y_train = load_pickle_file('../data/y_train_encode.pkl')
y_test = load_pickle_file('../data/y_test_encode.pkl')

# Modeling

In [4]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import precision_recall_fscore_support
import numpy as np

import xgboost as xgb



In [5]:
rfc = RandomForestClassifier(
    n_estimators=500,
    max_depth=30, 
    verbose=2,
    n_jobs=-1,
    class_weight='balanced_subsample',
    random_state=0
)

#rfc = SVC(probability=True, class_weight='balanced', verbose=True, random_state=0)
#rfc = xgb.XGBClassifier(max_depth=5, objective='multi:softprob', n_estimators=100)

model_name = 'rfr_500_trees_balance_subsample_1_2_words_v2'

In [6]:
rfc.fit(x_train, y_train)

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 12 concurrent workers.


building tree 1 of 500
building tree 2 of 500
building tree 3 of 500
building tree 4 of 500
building tree 5 of 500
building tree 6 of 500
building tree 7 of 500
building tree 8 of 500
building tree 9 of 500
building tree 10 of 500
building tree 11 of 500
building tree 12 of 500
building tree 13 of 500
building tree 14 of 500
building tree 15 of 500
building tree 16 of 500
building tree 17 of 500
building tree 18 of 500
building tree 19 of 500
building tree 20 of 500
building tree 21 of 500
building tree 22 of 500
building tree 23 of 500
building tree 24 of 500
building tree 25 of 500
building tree 26 of 500
building tree 27 of 500
building tree 28 of 500
building tree 29 of 500
building tree 30 of 500


[Parallel(n_jobs=-1)]: Done  17 tasks      | elapsed:  1.4min


building tree 31 of 500
building tree 32 of 500
building tree 33 of 500
building tree 34 of 500
building tree 35 of 500
building tree 36 of 500
building tree 37 of 500
building tree 38 of 500
building tree 39 of 500
building tree 40 of 500
building tree 41 of 500
building tree 42 of 500
building tree 43 of 500
building tree 44 of 500
building tree 45 of 500
building tree 46 of 500
building tree 47 of 500
building tree 48 of 500
building tree 49 of 500
building tree 50 of 500
building tree 51 of 500
building tree 52 of 500
building tree 53 of 500
building tree 54 of 500
building tree 55 of 500
building tree 56 of 500
building tree 57 of 500
building tree 58 of 500
building tree 59 of 500
building tree 60 of 500
building tree 61 of 500
building tree 62 of 500
building tree 63 of 500
building tree 64 of 500
building tree 65 of 500
building tree 66 of 500
building tree 67 of 500
building tree 68 of 500
building tree 69 of 500
building tree 70 of 500
building tree 71 of 500
building tree 72

[Parallel(n_jobs=-1)]: Done 138 tasks      | elapsed:  8.5min


building tree 151 of 500
building tree 152 of 500
building tree 153 of 500
building tree 154 of 500
building tree 155 of 500
building tree 156 of 500
building tree 157 of 500
building tree 158 of 500
building tree 159 of 500
building tree 160 of 500
building tree 161 of 500
building tree 162 of 500
building tree 163 of 500
building tree 164 of 500
building tree 165 of 500
building tree 166 of 500
building tree 167 of 500
building tree 168 of 500
building tree 169 of 500
building tree 170 of 500
building tree 171 of 500
building tree 172 of 500
building tree 173 of 500
building tree 174 of 500
building tree 175 of 500
building tree 176 of 500
building tree 177 of 500
building tree 178 of 500
building tree 179 of 500
building tree 180 of 500
building tree 181 of 500
building tree 182 of 500
building tree 183 of 500
building tree 184 of 500
building tree 185 of 500
building tree 186 of 500
building tree 187 of 500
building tree 188 of 500
building tree 189 of 500
building tree 190 of 500


[Parallel(n_jobs=-1)]: Done 341 tasks      | elapsed: 20.8min


building tree 354 of 500
building tree 355 of 500
building tree 356 of 500
building tree 357 of 500
building tree 358 of 500
building tree 359 of 500
building tree 360 of 500
building tree 361 of 500
building tree 362 of 500
building tree 363 of 500
building tree 364 of 500
building tree 365 of 500
building tree 366 of 500
building tree 367 of 500
building tree 368 of 500
building tree 369 of 500
building tree 370 of 500
building tree 371 of 500
building tree 372 of 500
building tree 373 of 500
building tree 374 of 500
building tree 375 of 500
building tree 376 of 500
building tree 377 of 500
building tree 378 of 500
building tree 379 of 500
building tree 380 of 500
building tree 381 of 500
building tree 382 of 500
building tree 383 of 500
building tree 384 of 500
building tree 385 of 500
building tree 386 of 500
building tree 387 of 500
building tree 388 of 500
building tree 389 of 500
building tree 390 of 500
building tree 391 of 500
building tree 392 of 500
building tree 393 of 500


[Parallel(n_jobs=-1)]: Done 500 out of 500 | elapsed: 30.4min finished


RandomForestClassifier(class_weight='balanced_subsample', max_depth=30,
                       n_estimators=500, n_jobs=-1, random_state=0, verbose=2)

In [15]:
#rfc.set_params(n_jobs=1)
#save_pickle_file(rfc, f'../models/{model_name}.pkl')

True

In [10]:
rfc = load_pickle_file(f'../models/{model_name}.pkl')

In [7]:
def split_array(arr:np.array, chunk_size:int):
    for idx in range(0, arr.shape[0], chunk_size):
        yield arr[idx: idx + chunk_size]

In [8]:
# get rid of the status updates for training
rfc.set_params(verbose=0)

selected_data = x_train
chunksize = 100000


total_iter = round(selected_data.shape[0] / chunksize)

y_pred = []
y_pred_proba = []
for chunk in tqdm(split_array(selected_data, chunksize), total=total_iter):
    #preds = rfc.predict(chunk)
    preds_proba = rfc.predict_proba(chunk)
    preds = np.argmax(preds_proba, axis=-1)
    for pred, proba in zip(preds, preds_proba):
        y_pred.append(pred)
        y_pred_proba.append(proba)

save_pickle_file(y_pred, f'../models/{model_name}_train_pred.pkl')
save_pickle_file(y_pred_proba, f'../models/{model_name}_train_pred_proba.pkl')

del y_pred
del y_pred_proba

  0%|          | 0/49 [00:00<?, ?it/s]

: 

: 

In [ ]:
# get rid of the status updates for training
rfc.set_params(verbose=0)

print("STARTING TEST SET")
selected_data = x_test
chunksize = 100000
total_iter = round(selected_data.shape[0] / chunksize)

y_pred_test = []
y_pred_proba_test = []
for chunk in tqdm(split_array(selected_data, chunksize), total=total_iter):
    #preds = rfc.predict(chunk)
    preds_proba = rfc.predict_proba(chunk)
    preds = np.argmax(preds_proba, axis=-1)
    for pred, proba in zip(preds, preds_proba):
        y_pred_test.append(pred)
        y_pred_proba_test.append(proba)



save_pickle_file(y_pred_test, f'../models/{model_name}_test_pred_.pkl')
save_pickle_file(y_pred_proba_test, f'../models/{model_name}_test_pred_proba.pkl')

del y_pred_test
del y_pred_proba_test

STARTING TEST SET


  0%|          | 0/12 [00:00<?, ?it/s]

True

In [12]:
y_pred = load_pickle_file(f'../models/{model_name}_train_pred.pkl')

In [18]:
precision, recall, f1_score, support = precision_recall_fscore_support(
    y_true=y_train,
    y_pred=y_pred)

In [19]:
len(y_test)

4902816

In [20]:
len(y_pred_test)

1225705

In [16]:
precision_test, recall_test, f1_score_test, support_test = precision_recall_fscore_support(
    y_true=y_test,
    y_pred=y_pred_test)

np.mean(recall_test)

ValueError: Found input variables with inconsistent numbers of samples: [4902816, 1225705]

In [19]:
np.mean(recall)

0.43839751130434185

In [11]:
np.mean(recall)

0.4606081746711068

In [12]:
np.mean(precision)

0.38122564314012475

In [18]:
np.corrcoef(precision, support)

array([[1.        , 0.34111568],
       [0.34111568, 1.        ]])

In [21]:
y_pred_proba

AttributeError: 'list' object has no attribute 'shape'

In [ ]:
precision, recall, f1_score, support = precision_recall_fscore_support(
    y_true=y_train,
    y_pred=y_pred)

In [15]:
support

array([  1743,    599,    184,   1073,  10171,  18081,   6246,   7303,
          276,  42842,   5374,   1340,    526,   9792,    768,  18745,
        45099,  19394,   1630,    393,   3349,   1545,  11504,  23298,
        20096,  26462,    149,   3222,  75393,    426,    203,   1101,
          552,  23855,    381,   9049,   6997,    332,    107,    676,
         2294,   4106,   6227,   1626,     13,   6027,  37252,    742,
        13238,    190,   3913,   1059,   9334,   2276,    559,   3736,
          514,   1825,  23550,   3245,    386,  59926,   3978,   8858,
         2629,   3551,   4544,  11793,   2591,   2162,    234,   9852,
         9696,   1986,   2757,   5437,  15527,   1011,  26466,     83,
        29594,    277,    898,  29937,   2330,  18278,   6483,    762,
          419,    538,   4208,   4696,    223,   5231,   6922,   6000,
         1273,   1730,  10227,   1985,   1226,    464,    538,  16009,
         9506,   6892,    915, 192676, 227066,   1209,   1919,   1147,
      

In [14]:
np.mean(recall)

0.27307692225470875

In [13]:
np.round(recall, 3)

array([0.127, 0.265, 0.484, 0.275, 0.054, 0.267, 0.04 , 0.452, 0.576,
       0.003, 0.291, 0.417, 0.337, 0.041, 0.285, 0.219, 0.019, 0.507,
       0.154, 0.331, 0.405, 0.353, 0.133, 0.066, 0.372, 0.121, 0.738,
       0.236, 0.187, 0.519, 0.389, 0.321, 0.089, 0.422, 0.205, 0.528,
       0.079, 0.59 , 0.673, 0.473, 0.2  , 0.189, 0.218, 0.077, 0.231,
       0.294, 0.153, 0.296, 0.37 , 0.226, 0.209, 0.286, 0.131, 0.256,
       0.131, 0.099, 0.442, 0.312, 0.19 , 0.178, 0.959, 0.005, 0.282,
       0.456, 0.55 , 0.161, 0.096, 0.134, 0.256, 0.285, 0.265, 0.569,
       0.105, 0.14 , 0.432, 0.327, 0.099, 0.408, 0.157, 0.747, 0.007,
       0.484, 0.233, 0.318, 0.442, 0.123, 0.158, 0.495, 0.52 , 0.253,
       0.061, 0.029, 0.525, 0.155, 0.171, 0.309, 0.401, 0.282, 0.102,
       0.052, 0.38 , 0.112, 0.074, 0.011, 0.433, 0.282, 0.424, 0.006,
       0.004, 0.06 , 0.413, 0.183, 0.125, 0.228, 0.225, 0.334, 0.101,
       0.169, 0.259, 0.202, 0.081, 0.227, 0.372, 0.005, 0.202, 0.256,
       0.129, 0.558,

In [1]:
np.round(precision, 3)

NameError: name 'np' is not defined

In [58]:
np.mean(precision)

0.6491155131159356